# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ed3466c0aa6b9355d2c77cd695fa5ccb69ee78094e19f8fee541ebf312247ec5aa21ac4d53fda292de103ce155999dcc7be628545e07e4d4c93346ccab6f3de

test:
  secret_key_base: 6853b4f31ea093257e3ce308c9ceb8d1fec61feaac36077264b4613f56443c582e6b97135d6a7ed78f46d2b4cf0d0231b22265ed0e02bd303c9c8649736fb54e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
